### ISSUE TITLE
./darknet data/ronaldo.jpg     

### ISSUE THREAD

**Issue by UESTCtubiao** [Evangeb/yolov3#2]
when i run "./darknet data/ronaldo.jpg"   always wrong!

Upsample Forward Layer
terminate called after throwing an instance of 'c10::Error'
  what():  It is expected output_size equals to 2, but got size 1 (upsample_bilinear2d_out_cpu_template at /pytorch/aten/src/ATen/native/UpSampleBilinear2d.cpp:165)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f8eaea5e441 in /home/tb/Downloads/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f8eaea5dd7a in /home/tb/Downloads/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0xa760b4 (0x7f8ea4a610b4 in /home/tb/Downloads/libtorch/lib/libcaffe2.so)

What caused it?thank you very much!

**Comment by UESTCtubiao** [comment]
./darknet data/ronaldo.jpg
is the final result?

**Comment by Evangeb** [comment]
that is the command to run the network.  In terms of the error I wrote this with a beta version of pytorch c++ so it would be hard to determine where that error is coming from on your end.
